language: python
python: 3.4
env:
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'